### PR TITLE
Preventing the tool focusing from unaquiring

### PR DESCRIPTION
**Pull request by jcdickinson**
Fixed the issue with the focus stealing

### CODE REVIEW

**Comment by shanselman** [comment]
You're a gentleman and a scholar.

**Comment by shanselman** [comment]
I'm not seeing that this is fixed. Nothing has changed. The app still runs away and the buttons still can't be pressed. Did you test it? (not trying to look a gift pull request in the mouth, though.)

**Comment by shanselman** [comment]
Hm, I'm going to have to roll this back. It's close but I'm still unable to actually press the buttons.

**Comment by jcdickinson** [comment]
Sorry Scott, work is in the way of me looking at this at the moment. I tested it with the version of Lync that I was running (2007 or something) - although I have 2013 now so I can test it with that.

**Comment by shanselman** [comment]
Awesome. Looking forward to learning from you.

On Wed, Nov 21, 2012 at 11:43 PM, Jonathan Dickinson <
notifications@github.com> wrote:

> Sorry Scott, work is in the way of me looking at this at the moment. I
> tested it with the version of Lync that I was running (2007 or something) -
> although I have 2013 now so I can test it with that.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shanselman/PanTiltZoomSystem/pull/3#issuecomment-10625996.

## 

Scott Hanselman
Help me? http://hnsl.mn/fightdiabetes

**Pull request merged**
