### PR TITLE
Event Handler unregistration

### PR DESCRIPTION
**Pull request by cgleadall**
Modified @gshackles work in the RemoteView.cs in the iOS project to unregister the 6 delegate event handlers. Work based on Xamarin Evolve conference session on Memory Management: good GC-friendly practice to unregister the event handlers.

### CODE REVIEW

**Comment by shanselman** [comment]
I defer to @gshackles Doe this look good?

**Comment by gshackles** [comment]
This looks ok to me, though I'm curious why `RefreshButton` is a public property on the class?

**Comment by cgleadall** [comment]
Sorry @gshackles, you are right... There is no need for the RefreshButton to be public. I moved it from a scoped variable in ViewDidLoad and accidently made it a public class-level property.

So, I will fix that, and then make a new Pull request?

**Comment by gshackles** [comment]
No worries @cgleadall, was just making sure I wasn't missing something :smile: 

If you update your branch the pull request will automatically be updated as well.

**Comment by cgleadall** [comment]
@gshackles update is complete. This one-liner change is ready for your approval.

**Pull request merged**
